# Generated by Django 3.2.13 on 2024-01-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_purchase_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
